$forwarded_ports={80=>8080}
  
Vagrant.configure("2") do |config|
	config.vm.box = "coreos-alpha"
        config.vm.network "private_network", ip: "192.168.33.11"
	
	$forwarded_ports.each do |guest, host|
        	config.vm.network "forwarded_port", guest: guest, host: host, auto_correct: true
      	end
	config.vm.provision :file, :source => "user-data.yml", :destination => "/tmp/vagrantfile-user-data"
        config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
end
