  
Vagrant.configure("2") do |config|
	config.vm.box = "coreos-alpha"
        config.vm.network "private_network", ip: "192.168.33.11"
	
	config.vm.provision :file, :source => "user-data.yml", :destination => "/tmp/vagrantfile-user-data"
        config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
	
        config.vm.provision :file, source: "./certificats", destination: "/tmp/ssl"
		
	config.vm.provision :shell, :inline => "mkdir -p /etc/kubernetes ;mv /tmp/ssl /etc/kubernetes/ssl", :privileged => true
	config.vm.provision :shell, :inline => "chmod 600 /etc/kubernetes/ssl/*-key.pem", :privileged => true
	config.vm.provision :shell, :inline => "chown -R root:root /etc/kubernetes/ssl", :privileged => true
	config.vm.provision :shell, :inline => "cd /etc/kubernetes/ssl/; ln -s tatoone-worker.pem worker.pem", :privileged => true
	config.vm.provision :shell, :inline => "cd /etc/kubernetes/ssl/; ln -s tatoone-worker-key.pem worker-key.pem", :privileged => true
end
